const CRICKETERS = [
  { name: "Virat Kohli", basePrice: 20 },
  { name: "Rohit Sharma", basePrice: 18 },
  { name: "Jasprit Bumrah", basePrice: 17 },
  { name: "Hardik Pandya", basePrice: 16 },
  { name: "Ravindra Jadeja", basePrice: 15 },
  { name: "KL Rahul", basePrice: 14 },
  { name: "Shubman Gill", basePrice: 13 },
  { name: "Suryakumar Yadav", basePrice: 12 },
  { name: "Shreyas Iyer", basePrice: 11 },
  { name: "Mohammed Shami", basePrice: 10 },
  { name: "Kuldeep Yadav", basePrice: 9 },
  { name: "Yuzvendra Chahal", basePrice: 9 },
  { name: "Axar Patel", basePrice: 9 },
  { name: "Ishan Kishan", basePrice: 8 },
  { name: "Ruturaj Gaikwad", basePrice: 8 },
  { name: "Prithvi Shaw", basePrice: 7 },
  { name: "Sanju Samson", basePrice: 7 },
  { name: "Rahul Tripathi", basePrice: 7 },
  { name: "Deepak Chahar", basePrice: 6 },
  { name: "Arshdeep Singh", basePrice: 6 },
  { name: "Shardul Thakur", basePrice: 6 },
  { name: "Washington Sundar", basePrice: 6 },
  { name: "Bhuvneshwar Kumar", basePrice: 6 },
  { name: "Umran Malik", basePrice: 5 },
  { name: "Mohammed Siraj", basePrice: 5 },
  { name: "Varun Chakravarthy", basePrice: 5 },
  { name: "Harshal Patel", basePrice: 5 },
  { name: "Dinesh Karthik", basePrice: 4 },
  { name: "Wriddhiman Saha", basePrice: 4 },
  { name: "Mayank Agarwal", basePrice: 4 },
  { name: "Devdutt Padikkal", basePrice: 4 },
  { name: "Tilak Varma", basePrice: 4 },
  { name: "Venkatesh Iyer", basePrice: 4 },
  { name: "Rahul Tewatia", basePrice: 4 },
  { name: "Ravi Bishnoi", basePrice: 4 },
  { name: "Shivam Dube", basePrice: 3 },
  { name: "Abhishek Sharma", basePrice: 3 },
  { name: "Sai Sudharsan", basePrice: 3 },
  { name: "T Natarajan", basePrice: 3 },
  { name: "Ajinkya Rahane", basePrice: 3 },
  { name: "Cheteshwar Pujara", basePrice: 2 }
];

module.exports = { CRICKETERS };

